// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nfse_backend.Data;

#nullable disable

namespace nfsebackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250916023553_AddDescontoToServicoItem")]
    partial class AddDescontoToServicoItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("nfse_backend.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Bairro")
                        .HasColumnType("longtext");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cep")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoMunicipio")
                        .HasColumnType("longtext");

                    b.Property<decimal>("DefaultIbsRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("InscricaoMunicipal")
                        .HasColumnType("longtext");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Logradouro")
                        .HasColumnType("longtext");

                    b.Property<string>("Municipio")
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.Property<string>("Uf")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("nfse_backend.Models.Nfse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Servicos")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Nfses");
                });

            modelBuilder.Entity("nfse_backend.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<decimal>("IBSRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("nfse_backend.Models.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("IBSRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("nfse_backend.Models.Nfse", b =>
                {
                    b.OwnsOne("nfse_backend.Models.InformacoesAdicionais", "InformacoesAdicionais", b1 =>
                        {
                            b1.Property<Guid>("NfseId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("CodigoTributacaoMunicipal")
                                .HasColumnType("longtext");

                            b1.Property<string>("FormaPagamento")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("MunicipioPrestador")
                                .HasColumnType("longtext");

                            b1.Property<string>("Observacoes")
                                .HasColumnType("longtext");

                            b1.Property<string>("ProtocoloEnvio")
                                .HasColumnType("longtext");

                            b1.HasKey("NfseId");

                            b1.ToTable("Nfses");

                            b1.WithOwner()
                                .HasForeignKey("NfseId");
                        });

                    b.OwnsOne("nfse_backend.Models.Prestador", "Prestador", b1 =>
                        {
                            b1.Property<Guid>("NfseId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Bairro")
                                .HasColumnType("longtext");

                            b1.Property<string>("Cep")
                                .HasColumnType("longtext");

                            b1.Property<string>("Cnpj")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("CodigoMunicipio")
                                .HasColumnType("longtext");

                            b1.Property<string>("Email")
                                .HasColumnType("longtext");

                            b1.Property<string>("InscricaoMunicipal")
                                .HasColumnType("longtext");

                            b1.Property<string>("Logradouro")
                                .HasColumnType("longtext");

                            b1.Property<string>("Municipio")
                                .HasColumnType("longtext");

                            b1.Property<string>("Numero")
                                .HasColumnType("longtext");

                            b1.Property<string>("RazaoSocial")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Telefone")
                                .HasColumnType("longtext");

                            b1.Property<string>("Uf")
                                .HasColumnType("longtext");

                            b1.HasKey("NfseId");

                            b1.ToTable("Nfses");

                            b1.WithOwner()
                                .HasForeignKey("NfseId");
                        });

                    b.OwnsOne("nfse_backend.Models.Tomador", "Tomador", b1 =>
                        {
                            b1.Property<Guid>("NfseId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Bairro")
                                .HasColumnType("longtext");

                            b1.Property<string>("Cep")
                                .HasColumnType("longtext");

                            b1.Property<string>("CpfCnpj")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Email")
                                .HasColumnType("longtext");

                            b1.Property<string>("Logradouro")
                                .HasColumnType("longtext");

                            b1.Property<string>("Municipio")
                                .HasColumnType("longtext");

                            b1.Property<string>("NomeRazaoSocial")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Numero")
                                .HasColumnType("longtext");

                            b1.Property<string>("Telefone")
                                .HasColumnType("longtext");

                            b1.Property<string>("Uf")
                                .HasColumnType("longtext");

                            b1.HasKey("NfseId");

                            b1.ToTable("Nfses");

                            b1.WithOwner()
                                .HasForeignKey("NfseId");
                        });

                    b.Navigation("InformacoesAdicionais")
                        .IsRequired();

                    b.Navigation("Prestador")
                        .IsRequired();

                    b.Navigation("Tomador")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
